acme_permission:
    resource: "@AcmePermissionBundle/Resources/config/routing.yml"
    prefix:   /
login:
    path: /login
    defaults: { _controller: AcmePermissionBundle:Security:login }
login_check:
    path: function/login_check
logout:
    path: function/logout

