<?php

namespace Acme\PermissionBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StaffController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:/xampp/htdocs/permission/app/cache/dev/jms_diextra/proxies/Acme-PermissionBundle-Controller-StaffController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Acme\\PermissionBundle\\Controller\\StaffController' => array('statisticProfileAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyd8391c92_feaa30eb00c5b07b42198467e8d8e188acb73cff\__CG__\Acme\PermissionBundle\Controller\StaffController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
